[DRAFT] Assessment Management | List of Assessments (MVP) - Frontend
snhuproduct/toboggan-ws pull request #104
Opened 2022-11-04 23:58 UTC by artem-sada

### Description

- create assessment page
- add cell types
- create assessment-evaluated-list

### Video or Screenshots

#### Screenshots

<img width="1728" alt="Screen Shot 2022-11-04 at 5 55 19 PM" src="https://user-images.githubusercontent.com/110631003/200090797-0761969d-bc03-4058-ba5a-df5192ae63b5.png">
<img width="1728" alt="Screen Shot 2022-11-04 at 5 55 35 PM" src="https://user-images.githubusercontent.com/110631003/200090801-d5684b2e-685d-415b-823a-e846dce40a5d.png">
<img width="1440" alt="Screen Shot 2022-11-04 at 5 55 48 PM" src="https://user-images.githubusercontent.com/110631003/200090803-cd82748d-213b-4d7c-89b9-1ba6314cc3ec.png">

### Other Details

- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-1985)

#### Checklist

- [X] **Assumptions of User Story met (including acceptance criteria)**
- [ ] **All new necessary Unit tests were CREATED** to promote code coverage
- [ ] **All required unit tests are PASSING**
- [X] The proposed functionality was tested manually locally, and it's working fine.
- [ ] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [X] Unnecessary console.logs AND/OR comments were removed
- [X] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [ ] Ensure configuration and/or build changes documented

2022-11-07 19:14 UTC, joao-sd submitted a review, later dismissed
Hey Artem, it's looking good!

I left only a couple of comments, but nothing that should be a blocker.

Tests are not passing also, so please fix it before merging.

2022-11-07 19:14 UTC, joao-sd commented on apps/toboggan-app/src/app/assessment/components/assessment-evaluated-list/assessment-evaluated-list.component.scss
> +//     .table-container {
Please delete this file

2022-11-07 19:14 UTC, joao-sd commented on apps/toboggan-app/src/app/assessment/components/assessment-evaluated-list/assessment-evaluated-list.component.ts
> +          // this.users = dataGeneratorFactoryOutput.rawData as IUser[];
Commented out left over?

2022-11-07 19:14 UTC, joao-sd commented on apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.scss
> +//         background: #fff;
Please delete this file

2022-11-07 22:12 UTC, artem-sada commented on apps/toboggan-app/src/app/assessment/components/assessment-evaluated-list/assessment-evaluated-list.component.ts
> +          // this.users = dataGeneratorFactoryOutput.rawData as IUser[];
`asessment-evaludated` folder is removed, will be create in another PR

2022-11-07 22:14 UTC, artem-sada commented
> Hey Artem, it's looking good!
> 
> I left only a couple of comments, but nothing that should be a blocker.
> 
> Tests are not passing also, so please fix it before merging.

All tests related with this task are correct, it is the failing tests from `main` branch

2022-11-08 04:10 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.html
> +    noResultsHeading="No groups yet"
Could you please update  "noResultsHeading" text ?

2022-11-08 22:57 UTC, artem-sada commented on apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.html
> +    noResultsHeading="No groups yet"
Resolved

2022-11-09 04:31 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.ts
> +    if (this.groupService.groupUpdated$) {
is this part really needed. ?  its group related code right. ?

2022-11-09 04:31 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.ts
> +    [this.datageneratorSubscription, this.updateGroupSubscription].map((s) => {
please update subscription names 
"updateGroupSubscription"

2022-11-09 04:32 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.ts
> +        this.router.navigate([`/group/details/${groupId}`], {
i believe we will have a different kind link, not group group related

2022-11-09 04:32 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.ts
> +        this.openDeleteGroupConfirmation(rowData.cellData as unknown as IAssessment);
I think we don't need it

2022-11-09 04:33 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.ts
> +    const groups = fetchedData as IAssessment[];
please update variable names according to the context

2022-11-09 04:33 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.ts
> +        groupTableHeader,
please update variable names according to context  - assessments

2022-11-09 04:34 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-table.type.ts
> +  {
Update variable name

2022-11-09 04:35 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/pages/assessment-main-page/assessment-main-page.component.spec.ts
> +  it('should open add user to group modal', () => {
this test case is not needed

2022-11-09 04:36 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/pages/assessment-main-page/assessment-main-page.component.ts
> +  @ViewChild('addUsers') addUsersTemplRef?: ElementRef;
Please verify contents of this component , most of the parts are not needed for assessments

2022-11-09 04:37 UTC, sada-ajith commented on apps/toboggan-app/src/app/assessment/services/assessment.service.ts
> +    "time_left": { value: "-10hr 30m", cellClass: 'gp-red-20' },
Can we move this to Nestjs service and serve from there , so that once APIs are ready ,we only need to update api end point

2022-11-09 04:38 UTC, sada-ajith requested changes
I've added few comments  - in details , please correct those items

2022-11-10 17:21 UTC, mk-sada reviewed
Thank you so much for fixing the pipeline automated test failures. 
I will review this shortly (13:30-14:00 EST). Hopefully any additional change you need to make will be done by then.

2022-11-10 20:19 UTC, mk-sada approved these changes
Good work! 

@joao-sd , @sada-ajith , would you mind re-reviewing this to get folks unblocked?

2022-11-11 07:08 UTC, sada-ajith commented
@mk-sada  most of the items were resolved , few typos were there, I fixed it and pushed, as few offshore tickers are blocking . I'm merging this PR as well
CC @joao-sd

2022-11-11 07:08 UTC, sada-ajith approved these changes

2022-11-11 07:09 UTC, merged