Snhut 2386 edit user api
snhuproduct/toboggan-ws pull request #109
Opened 2022-11-15 06:43 UTC by pran-sada

### Description

- Please write a short description of your changes here. Provide as much context as needed.

### Video or Screenshots

#### Video

- Paste your link here.

#### Screenshots

| Original | Updated |
| -------- | ------- |
|          |         |

### Other Details

- [JIRA Ticket](https://JIRA_LINK_HERE)

#### Checklist

- [ ] **Assumptions of User Story met (including acceptance criteria)**
- [ ] **All new necessary Unit tests were CREATED** to promote code coverage
- [ ] **All required unit tests are PASSING**
- [ ] The proposed functionality was tested manually locally, and it's working fine.
- [ ] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [ ] Unnecessary console.logs AND/OR comments were removed
- [ ] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [ ] Ensure configuration and/or build changes documented

2022-11-15 06:59 UTC, sada-ajith commented on apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.spec.ts
> +    expect(component.userForm.controls.firstName.value).toBe('Bob');
Lines 51-53 can be combined into a single expect statement,

2022-11-15 07:00 UTC, sada-ajith commented on apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.spec.ts
> +    expect(component.userForm.controls.firstName.value).toBe('');
Lines 64-67 can be combined into a single expect statement,

2022-11-15 07:00 UTC, sada-ajith commented on apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.spec.ts
> +   expect(component.userForm.controls.firstName.value).not.toBeTruthy();
Lines 77-79 can be combined into a single expect statement,

2022-11-15 07:03 UTC, sada-ajith commented
Please add unit test cases related to form validation

2022-11-15 07:04 UTC, sada-ajith requested changes
Please see my observations and fix it

2022-11-15 14:46 UTC, pran-sada commented on apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.spec.ts
> +    expect(component.userForm.controls.firstName.value).toBe('Bob');
Combined into single expect statement

2022-11-15 14:47 UTC, pran-sada commented on apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.spec.ts
> +    expect(component.userForm.controls.firstName.value).toBe('');
combined into a single expect statement

2022-11-15 14:47 UTC, pran-sada commented on apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.spec.ts
> +   expect(component.userForm.controls.firstName.value).not.toBeTruthy();
combined into a single expect statement

2022-11-17 06:52 UTC, sada-ajith approved these changes
approved

2022-11-17 15:59 UTC, merged