SNHUT-575, SNHUT-583 - User editing
snhuproduct/toboggan-ws pull request #18
Opened 2022-08-04 23:28 UTC by david-mart

https://user-images.githubusercontent.com/20728627/182971940-a079b54d-6dac-453e-b44b-6146a7074bb4.mov

2022-08-05 00:31 UTC, joao-sd commented on apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.ts
> +        console.log('User updated');
Can we remove these console logs?

2022-08-05 00:31 UTC, joao-sd commented on apps/toboggan-app/src/app/shared/components/modal/modal.component.ts
> +      console.log('object');
Please remove these console logs

2022-08-05 00:32 UTC, joao-sd requested changes
Hey David, that's a great piece of work!
I left a couple of comments regarding some console logs leftovers, but overall, it's excellent.

Thanks

2022-08-09 15:36 UTC, joao-sd approved these changes
LGTM!

2022-08-09 20:09 UTC, dmitriy-rodimin-sada commented
Interesting way of using Modal Component from Toboggan UI directly bypassing the Modal Directive. Seems more re-usable than the pattern I came with for Create User. Will try this pattern next time. I assume the instance of the BsModalService would be the same one as injected in the Toboggan UI Allert Banner since it is checking it to hide banner when any modals are shown.

2022-08-09 20:09 UTC, dmitriy-rodimin-sada approved these changes

2022-08-23 07:35 UTC, sada-ajith commented
@david-mart  could you please resolve conflicts and merge code  ?

2022-08-24 21:37 UTC, merged