Snhut 584 user deactivate user account
snhuproduct/toboggan-ws pull request #24
Opened 2022-08-15 18:05 UTC by joao-sd

2022-08-15 19:31 UTC, mk-sada approved these changes
Separating user-table data-types was a nice touch!

PS/Note: This will require `rm -rf node_modules package-lock && npm install` to work properly.

2022-08-15 21:21 UTC, dmitriy-rodimin-sada commented on apps/toboggan-app/src/app/shared/services/user/user.service.ts
> +  updateUser(updatedUser: IUpdatedUser, userId: string): void {
I think you would want to await the execution of this method in your component code. You can see how it is done above for the createNewUser. You can return a promise.

2022-08-15 21:23 UTC, dmitriy-rodimin-sada requested changes

2022-08-15 21:23 UTC, dmitriy-rodimin-sada commented on apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
> +    this.refreshTableData();
if you don't await on 167, the 175 will run before user updates

2022-08-15 23:10 UTC, joao-sd commented on apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
> +    this.refreshTableData();
Done

2022-08-16 13:50 UTC, dmitriy-rodimin-sada approved these changes

2022-08-16 14:00 UTC, merged