SNHUT-1235 : User Management | Add new user to an existing user group - Frontend
snhuproduct/toboggan-ws pull request #75
Opened 2022-09-23 14:52 UTC by hilal-sadaindia

### Description

- User Management | Add new user to an existing user group - Frontend

### Video or Screenshots

#### Video

- Paste your link here.

#### Screenshots

| Original | Updated |
| -------- | ------- |
|          |         |

### Other Details

- [SNHUT-1235](https://collectiveshift.atlassian.net/browse/SNHUT-1235)

#### Checklist

- [ ] **Assumptions of User Story met (including acceptance criteria)**
- [ ] **All new necessary Unit tests were CREATED** to promote code coverage
- [ ] **All required unit tests are PASSING**
- [ ] The proposed functionality was tested manually locally, and it's working fine.
- [ ] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [ ] Unnecessary console.logs AND/OR comments were removed
- [ ] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [ ] Ensure configuration and/or build changes documented

2022-09-25 21:00 UTC, hilal-sadaindia commented
<img width="1728" alt="Screenshot 2022-09-26 at 2 15 26 AM" src="https://user-images.githubusercontent.com/111114994/192165419-b800e759-45cf-4fdc-bbf8-5ca968a7800b.png">

2022-09-27 06:45 UTC, sada-ajith commented on apps/toboggan-app/src/app/user/components/create-user/create-user.component.ts
> +    firstName: new FormControl('', [ Validators.required,
Add a field for user groups

2022-09-27 06:46 UTC, sada-ajith commented on apps/toboggan-app/src/app/user/components/create-user/create-user.component.ts
> +  userGroups: IGroup[] = mockGroups()
- [ ] use existing service for groups

2022-09-27 06:46 UTC, sada-ajith commented on apps/toboggan-app/src/app/user/components/create-user/create-user.component.ts
> +        userObj.groups = this.groups;
- [ ] make use of form groups instead of this pattern

2022-09-27 06:47 UTC, sada-ajith commented on apps/toboggan-app/src/app/user/components/mock/groupsMock.ts
> +import { v4 as uuidv4 } from 'uuid';
- [ ] you can remove this pattern as we are making use of existing service

2022-09-27 06:49 UTC, sada-ajith requested changes
Please see comments

2022-09-27 11:17 UTC, sada-ajith approved these changes
Approved

2022-09-27 11:30 UTC, merged